/* PoseidonRust — C ABI for the Rust toolchain spike.
 *
 * GENERATED by cbindgen from src/lib.rs — do not edit by hand.
 * Regenerated on every build; run `cargo build` (or the CMake build) to refresh.
 *
 * Ownership: any pointer returned by this API is owned by Rust and must be
 * released through the matching free function here, never the C/C++ allocator. */

#ifndef POSEIDON_RUST_H
#define POSEIDON_RUST_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ABI handshake value. C++ asserts the linked crate matches its header
// (`PRS_ABI_VERSION` in `poseidon_rust.h`). Bump on any breaking ABI change.
#define PRS_ABI_VERSION 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns [`PRS_ABI_VERSION`] as compiled into this crate.
int prs_abi_version(void);

// Trivial numeric round-trip: proves arguments and return values cross the
// boundary correctly. Wrapping add so it can never panic on overflow.
int prs_add(int a, int b);

// String round-trip demonstrating cross-language allocation ownership.
//
// Borrows a NUL-terminated UTF-8 string from C++ and returns a freshly
// allocated NUL-terminated string owned by Rust. The caller **must** return it
// to [`prs_string_free`]. Returns null on a null pointer, non-UTF-8 input, an
// embedded NUL, or a panic.
//
// # Safety
// `name` must be null or point to a valid NUL-terminated C string that stays
// alive for the duration of the call.
char *prs_greet(const char *name);

// Frees a string previously returned by [`prs_greet`]. Null is a no-op.
//
// # Safety
// `s` must be null, or a pointer returned by [`prs_greet`] that has not already
// been freed.
void prs_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* POSEIDON_RUST_H */
