/* PoseidonArchive — C ABI for reading OFP/Poseidon PBO archives.
 *
 * GENERATED by cbindgen from src/lib.rs — do not edit by hand.
 * Regenerated on every build; run `cargo build` (or the CMake build) to refresh.
 *
 * Backed by the standalone papa-bear-archive crate. Ownership: the handle from
 * pa_pbo_open*() is freed only by pa_pbo_close(); extracted bytes are copied into
 * the caller's buffer. Strings from pa_pbo_entry_name()/pa_last_error() are owned
 * by the library — do not free them. */

#ifndef POSEIDON_ARCHIVE_H
#define POSEIDON_ARCHIVE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle to a parsed PBO. Owns the archive plus a cache of NUL-terminated
// entry names, so [`pa_pbo_entry_name`] can return pointers that stay valid
// until [`pa_pbo_close`].
typedef struct PaPbo PaPbo;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Opens and parses a PBO from a filesystem path. Returns null on error; call
// [`pa_last_error`] for the reason.
//
// # Safety
// `path` must be null or a valid NUL-terminated string for the duration of the
// call.
struct PaPbo *pa_pbo_open(const char *path);

// Opens and parses a PBO from an in-memory buffer. Returns null on error.
//
// # Safety
// `data` must point to `len` readable bytes, or be null when `len` is 0.
struct PaPbo *pa_pbo_open_bytes(const uint8_t *data, int len);

// Frees a handle returned by `pa_pbo_open*`. Null is a no-op.
//
// # Safety
// `pbo` must be null, or a handle from `pa_pbo_open*` that has not been freed.
void pa_pbo_close(struct PaPbo *pbo);

// Number of file entries in the archive, or -1 if the handle is null.
//
// # Safety
// `pbo` must be null or a valid handle.
int pa_pbo_entry_count(const struct PaPbo *pbo);

// Logical name of entry `idx` (forward-slash separated), owned by the handle and
// valid until [`pa_pbo_close`]. Returns null if the handle is null or `idx` is
// out of range.
//
// # Safety
// `pbo` must be null or a valid handle.
const char *pa_pbo_entry_name(const struct PaPbo *pbo, int idx);

// Logical (decompressed) size in bytes of entry `idx`, or -1 on a null handle or
// out-of-range index.
//
// # Safety
// `pbo` must be null or a valid handle.
int pa_pbo_entry_size(const struct PaPbo *pbo, int idx);

// Extracts entry `idx`, decompressing if needed.
//
// Returns the entry's decompressed size in bytes. If `buffer` is null, the size
// is returned without copying (size query). Otherwise, when `buffer_size` is at
// least the entry size, the bytes are copied into `buffer` and the size is
// returned. Returns -1 on error (null handle, bad index, decode failure, or a
// non-null buffer that is too small); see [`pa_last_error`].
//
// # Safety
// `pbo` must be null or a valid handle. If non-null, `buffer` must point to at
// least `buffer_size` writable bytes.
int pa_pbo_extract(const struct PaPbo *pbo, int idx, uint8_t *buffer, int buffer_size);

// Last error message on the calling thread (empty string if none). Owned by the
// library; valid until the next failing call on this thread. Never null.
const char *pa_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* POSEIDON_ARCHIVE_H */
